#pragma once

#include <cstddef>
#include <cstdint>

void ggml_cuda_kvarn_store_body_reference_minmax(
        const float * k_tile,
        const float * v_tile,
        uint8_t * k_body,
        uint8_t * v_body,
        float * k_scales,
        float * v_scales,
        float * scratch, // at least head_dim*group_size + 2*max(head_dim, group_size) floats
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        uint32_t sinkhorn_iters,
        float rtn_quantile,
        void * stream);

void ggml_cuda_kvarn_store_body_pending_records_minmax(
        const float * pending_k,
        const float * pending_v,
        uint8_t * k_body,
        uint8_t * v_body,
        float * k_scales,
        float * v_scales,
        float * scratch,
        const int32_t * records,
        uint32_t n_record_batch,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        uint32_t sinkhorn_iters,
        float rtn_quantile,
        size_t k_body_record_stride_bytes,
        size_t v_body_record_stride_bytes,
        size_t k_body_head_stride_bytes,
        size_t v_body_head_stride_bytes,
        size_t k_scale_record_stride_floats,
        size_t v_scale_record_stride_floats,
        size_t k_scale_head_stride_floats,
        size_t v_scale_head_stride_floats,
        size_t pending_k_head_stride_floats,
        size_t pending_v_head_stride_floats,
        void * stream);

void ggml_cuda_kvarn_store_body_pending_heads_minmax(
        const float * pending_k,
        const float * pending_v,
        uint8_t * k_body,
        uint8_t * v_body,
        float * k_scales,
        float * v_scales,
        float * scratch,
        uint32_t n_heads,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        uint32_t sinkhorn_iters,
        float rtn_quantile,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        size_t pending_k_head_stride_floats,
        size_t pending_v_head_stride_floats,
        void * stream);

void ggml_cuda_kvarn_store_k_body_reference_minmax(
        const float * k_tile,
        uint8_t * k_body,
        float * k_scales,
        float * scratch, // at least head_dim*group_size + 2*max(head_dim, group_size) floats
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t sinkhorn_iters,
        float rtn_quantile,
        void * stream);

void ggml_cuda_kvarn_store_v_body_reference_minmax(
        const float * v_tile,
        uint8_t * v_body,
        float * v_scales,
        float * scratch, // at least head_dim*group_size + 2*max(head_dim, group_size) floats
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t value_bits,
        uint32_t sinkhorn_iters,
        float rtn_quantile,
        void * stream);

void ggml_cuda_kvarn_dequant_body(
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * k_out,
        float * v_out,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        void * stream);

void ggml_cuda_kvarn_dequant_body_n(
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * k_out,
        float * v_out,
        uint32_t n_records,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        size_t k_out_stride_floats,
        size_t v_out_stride_floats,
        void * stream);

// K f32 output in token-major layout (g*head_dim + d); V identical to
// ggml_cuda_kvarn_dequant_body_n. Used by the 512d warpqk attention path
// so per-lane K reads are coalesced.
void ggml_cuda_kvarn_dequant_body_n_k_token_major(
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * k_out,
        float * v_out,
        uint32_t n_records,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        size_t k_out_stride_floats,
        size_t v_out_stride_floats,
        void * stream);

// f16 outputs, token-major K (g*head_dim + d); used by the 512d warpqk
// attention path to halve body-scratch read traffic. k_out/v_out point to
// __half storage (void* to keep this header CUDA-type-free for hosts).
void ggml_cuda_kvarn_dequant_body_n_k_token_major_f16(
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        void * k_out,
        void * v_out,
        uint32_t n_records,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        size_t k_out_stride_elems,
        size_t v_out_stride_elems,
        void * stream);

void ggml_cuda_kvarn_qk_body(
        const float * q,
        const uint8_t * k_body,
        const float * k_scales,
        float * scores,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        float scale,
        void * stream);

void ggml_cuda_kvarn_av_body(
        const float * probs,
        const uint8_t * v_body,
        const float * v_scales,
        float * out,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t value_bits,
        void * stream);

void ggml_cuda_kvarn_attn_body(
        const float * q,
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * out,
        float * scores,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_body_n(
        const float * q,
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * out,
        float * scores,
        uint32_t n_records,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_body_n_batch(
        const float * q,
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        float * out,
        float * scores,
        uint32_t n_queries,
        uint32_t n_records,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t q_stride_floats,
        size_t out_stride_floats,
        size_t score_stride_floats,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_mixed(
        const float * q,
        const float * sink_k,
        const float * sink_v,
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        const float * tail_k,
        const float * tail_v,
        float * out,
        float * scores,
        uint32_t n_sink,
        uint32_t n_records,
        uint32_t n_tail,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t k_body_stride_bytes,
        size_t v_body_stride_bytes,
        size_t k_scale_stride_floats,
        size_t v_scale_stride_floats,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_mixed_f32_scratch(
        const float * q,
        const float * sink_k,
        const float * sink_v,
        const float * body_k,
        const float * body_v,
        const float * tail_k,
        const float * tail_v,
        float * out,
        float * scores,
        uint32_t n_sink,
        uint32_t n_records,
        uint32_t n_tail,
        uint32_t head_dim,
        uint32_t group_size,
        size_t k_body_stride_floats,
        size_t v_body_stride_floats,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_mixed_f16_batch_scratch(
        const float * q,
        const uint16_t * sink_tail_k,
        const uint16_t * sink_tail_v,
        const float * body_k,
        const float * body_v,
        const float * pending_k,
        const float * pending_v,
        const void * kq_mask,
        float * out,
        float * scores,
        uint32_t n_queries,
        uint32_t n_head,
        uint32_t n_head_kv,
        uint32_t n_sink,
        uint32_t n_records,
        uint32_t n_pending,
        uint32_t n_tail,
        uint32_t tail_start,
        uint32_t head_dim,
        uint32_t group_size,
        size_t q_stride_head_floats,
        size_t q_stride_query_floats,
        size_t out_stride_head_floats,
        size_t out_stride_query_floats,
        size_t sink_tail_stride_head_f16,
        size_t sink_tail_stride_token_f16,
        size_t pending_stride_head_floats,
        size_t pending_stride_token_floats,
        size_t k_body_stride_record_floats,
        size_t v_body_stride_record_floats,
        size_t k_body_stride_head_floats,
        size_t v_body_stride_head_floats,
        size_t kq_mask_stride_query_bytes,
        size_t kq_mask_stride_token_bytes,
        uint32_t kq_mask_type,
        float scale,
        void * stream);

void ggml_cuda_kvarn_attn_mixed_f16_batch(
        const float * q,
        const uint16_t * sink_tail_k,
        const uint16_t * sink_tail_v,
        const uint8_t * k_body,
        const uint8_t * v_body,
        const float * k_scales,
        const float * v_scales,
        const float * pending_k,
        const float * pending_v,
        const void * kq_mask,
        float * out,
        float * scores,
        uint32_t n_queries,
        uint32_t n_head,
        uint32_t n_head_kv,
        uint32_t n_sink,
        uint32_t n_records,
        uint32_t n_pending,
        uint32_t n_tail,
        uint32_t tail_start,
        uint32_t head_dim,
        uint32_t group_size,
        uint32_t key_bits,
        uint32_t value_bits,
        size_t q_stride_head_floats,
        size_t q_stride_query_floats,
        size_t out_stride_head_floats,
        size_t out_stride_query_floats,
        size_t sink_tail_stride_head_f16,
        size_t sink_tail_stride_token_f16,
        size_t pending_stride_head_floats,
        size_t pending_stride_token_floats,
        size_t k_body_stride_record_bytes,
        size_t v_body_stride_record_bytes,
        size_t k_body_stride_head_bytes,
        size_t v_body_stride_head_bytes,
        size_t k_scale_stride_record_floats,
        size_t v_scale_stride_record_floats,
        size_t k_scale_stride_head_floats,
        size_t v_scale_stride_head_floats,
        size_t kq_mask_stride_query_bytes,
        size_t kq_mask_stride_token_bytes,
        uint32_t kq_mask_type,
        float scale,
        void * stream);
